//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace allegroWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyIncomingPaymentsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MyIncomingPaymentsTable()
        {
            this.CategoryOfMyIncomingPaymentsTables = new HashSet<CategoryOfMyIncomingPaymentsTable>();
            this.PayTransDatailsTables = new HashSet<PayTransDatailsTable>();
        }
    
        public long PayTransID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<int> PayTransBuyerID { get; set; }
        public string PayTransType { get; set; }
        public string PayTransStatus { get; set; }
        public Nullable<double> PayTransAmount { get; set; }
        public Nullable<long> PayTransCreateDate { get; set; }
        public Nullable<long> PayTransRecvDate { get; set; }
        public Nullable<double> PayTransPrice { get; set; }
        public Nullable<int> PayTransCount { get; set; }
        public Nullable<double> PayTransPostageAmount { get; set; }
        public Nullable<int> PayTransIncomplete { get; set; }
        public Nullable<int> PayTransMainId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryOfMyIncomingPaymentsTable> CategoryOfMyIncomingPaymentsTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayTransDatailsTable> PayTransDatailsTables { get; set; }
    }
}
