//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace allegroWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoldItemsTable
    {
        public long ItemID { get; set; }
        public string ItemTitle { get; set; }
        public string ItemThumbnailUrl { get; set; }
        public Nullable<int> ItemPriceType { get; set; }
        public Nullable<double> ItemPriceValue { get; set; }
        public Nullable<int> ItemSoldQuantity { get; set; }
        public Nullable<int> ItemQuantityType { get; set; }
        public Nullable<long> ItemStartTime { get; set; }
        public Nullable<long> ItemEndTime { get; set; }
        public string ItemEndTimeLeft { get; set; }
        public Nullable<int> ItemBiddersCounter { get; set; }
        public Nullable<int> ItemCategoryId { get; set; }
        public Nullable<int> ItemWtchersCounter { get; set; }
        public Nullable<int> ItemViewsCounter { get; set; }
        public string ItemNote { get; set; }
        public Nullable<int> ItemShopInfo { get; set; }
        public Nullable<int> ItemPayInfo { get; set; }
    }
}
